-- MySQL Script generated by MySQL Workbench
-- Tue May 16 22:24:08 2017
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IMAP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IMAP` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `IMAP` ;

-- -----------------------------------------------------
-- Table `IMAP`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IMAP`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NULL,
  `accessLevel` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IMAP`.`Mailbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IMAP`.`Mailbox` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `User_id` INT NOT NULL,
  `parentId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Mailbox_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Mailbox_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `IMAP`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IMAP`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IMAP`.`Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `Mailbox_id` INT NOT NULL,
  `flagSeen` TINYINT(1) NULL,
  `flagAnswered` TINYINT(1) NULL,
  `flagDeleted` TINYINT(1) NULL,
  `flagDraft` TINYINT(1) NULL,
  `flagRecent` TINYINT(1) NULL,
  `flagFlagged` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Message_User1_idx` (`User_id` ASC),
  INDEX `fk_Message_Mailbox1_idx` (`Mailbox_id` ASC),
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `IMAP`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_Mailbox1`
    FOREIGN KEY (`Mailbox_id`)
    REFERENCES `IMAP`.`Mailbox` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
